# Generated by Django 5.0.7 on 2024-08-06 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(default='Default Last Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
